# -*- coding: utf-8 -*-
"""HackTJ9AI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15G1DpoPhWmZ5nOLpeS7O-DHSaCcdvHOW
"""

import pandas as pd
import sklearn
#from sklearn.model_selection import train_test_split
#from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.simplefilter('ignore', UserWarning)
train = pd.read_csv("final.csv")
X = train.drop(columns=['label'])
y = train['label']
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.15)
from warnings import simplefilter
simplefilter(action='ignore', category=FutureWarning)


knn = KNeighborsClassifier(n_neighbors=6) #Determined to be the most precise number
knn.fit(X,y)



desired = input("Hi! Enter the title of the article you would like to check: ")

desired_tofloat = "."

for x in desired:
  desired_tofloat += str(ord(x))

if(knn.predict([[desired_tofloat]]) == 0):
  print("This article has been flagged as suspicious by our database. We recommend checking with another source")
else:
  print("This article seems safe. To be sure you're getting a safe experience, check for reputable sources")